# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Segment series into adjacent regimes
#' 
#' @param Y Numeric. Vector to be segmented
#' 
#' @param K Integer. Number of segments. Defaults to 5.
#'
#' @param alpha Numeric. Critical value for F-statistic. Defaults to 0.05. 
#'
#' @param exact Logical. Skip reduction of time series. Defaults to FALSE. 
#'
#' @return Vector of integers specifying segmentation points of the series.
#'
#' @export
#'
segment <- function(Y, K = 5L, alpha = 0.05, exact = FALSE) {
    .Call('tsAnomaly_segment', PACKAGE = 'tsAnomaly', Y, K, alpha, exact)
}

